# Generated by Django 5.2.8 on 2025-11-14 15:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prelim_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Prelim grade (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('midterm_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Midterm grade (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Final grade (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prelim_weight', models.DecimalField(decimal_places=2, default=30.0, help_text='Prelim weight percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('midterm_weight', models.DecimalField(decimal_places=2, default=30.0, help_text='Midterm weight percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_weight', models.DecimalField(decimal_places=2, default=40.0, help_text='Final weight percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weighted_average', models.DecimalField(blank=True, decimal_places=2, help_text='Computed weighted average', max_digits=5, null=True)),
                ('letter_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='courses.enrollment')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('summer', 'Summer')], max_length=10)),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_units', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='gpa_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GPA',
                'verbose_name_plural': 'GPAs',
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('student', 'semester', 'academic_year')},
            },
        ),
    ]
