# Generated by Django 5.2.8 on 2025-11-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studentprofile_year_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='program',
        ),
    ]
