# Generated by Django 5.2.8 on 2025-11-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='specialization',
        ),
    ]
