# Generated by Django 5.2.8 on 2025-11-14 16:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code'], 'verbose_name': 'Course/Program', 'verbose_name_plural': 'Courses/Programs'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['course', 'year_level', 'semester', 'code'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='year_level',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='e.g., BSCS, BSIT', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='e.g., BS Computer Science', max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='e.g., IT101, CS201', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(help_text='Which program this subject belongs to (e.g., BSCS, BSIT)', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='e.g., Systems Analysis and Modeling', max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year_level',
            field=models.IntegerField(help_text='Which year this subject is taught (1=1st year, 2=2nd year, etc.)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
